//name:Mouhammed Ghosheh
//id Number: 322310509

#include <stdio.h>
#include <string.h>
int* CountFunc(char*);
void print();

int main() {
    print();
return 0;
}
void print(){       //this function is responsible for the input-output activity
    static int* result;  //an array that stores the answer
    char in[511];           //the input
    int count=0;
    char temp[511];
    FILE *fp;
    fp = fopen("File.txt","a+");
    if(fp==NULL){                           //check if file opening was successfull
        printf("Error opening file");
        return;
    }
    while (1) {                             //endless loop until it breaks from the "exit"
        printf("PLease Enter a word or \"exit\" to end the program\n");
        scanf("%[^\n]s", in);                       //record the input to in
        getchar();                                      //getchar() flushes the new line generated by scanf
        in[strlen(in)] = '\0';
        result = CountFunc(in);                         //stores all information about the string in this array
        if(result[3] == 1)                          //if the word exit was detected then stop
            break;
        if(result[2] == 1 ){                        //if the word history was detected:
            fclose(fp);
            fp = fopen("File.txt","r");     //these two lines reset the pointer in the file, so we can read from the beginning
            while(fgets(temp, 511, fp)) {           //temp is the word we are currently printing and count is for every word in the file until we finish
                temp[strlen(temp)] = '\0';
                printf("%d: %s",count,temp);
                count++;
            }
            count=0;                                    //reset the counter
            fclose(fp);                                 //reset the pointer
            fp = fopen("File.txt","a+");            //append again
        }
        else{
        fprintf(fp,"%s\n",in);                  //if neither of the keywords history or exit were detected then we just send the word into the file.txt,
                                                       //and then we print the information to that word

        printf("%d words\n%d Chars\n", result[0], result[1]);}  //result[0] is wordsNumber and result[1] is charNumber
    }

    fclose(fp);
}

//this function stores all the string information that we passed as an argument and returns an array that has all that information, first slot in the array
//is how many words are there in that string, second slot for how many chars,third is whether the word is history (1 if true, 0 if false) and the last one is
//for the exit keyword (1 if true, 0 if false)
//I made it so that it returns an array with all the results so that I pass through the string only one time and store all the information in one run
int* CountFunc(char* word) {
    int i = 0;
    while (word[i] == ' ')i++;
    static int result[4];
    int wordCount = 1;
    int charCount = 1;
    int ifHistory = 0;
    int ifExit = 0;
    for (; i < strlen(word); ++i) {

            if ((word[i] == 'h' && word[i + 1] == 'i' && word[i + 2] == 's' && word[i + 3] == 't' &&
                 word[i + 4] == 'o' && word[i + 5] == 'r' && word[i + 6] == 'y') &&
                (word[i + 7] == ' ' || word[i + 7] == '\0')) {      //check if history is detected and break if true
                ifHistory = 1;          //set the flag to one(detected!!)
                break;
            } else if ((word[i] == 'e' && word[i + 1] == 'x' && word[i + 2] == 'i' && word[i + 3] == 't') &&
                       (word[i + 4] == ' ' || word[i + 4] == '\0')) {   //check if history is detected and break if true
                ifExit = 1;             //set the flag to one(detected!!)
                break;
            }


            if (word[i] == ' ' && word[i + 1] != ' ' && word[i + 1] != '\0') {  //count words
                wordCount++;

        }
            if (word[i + 1] != ' ' && word[i + 1] != '\0') {                    //count chars
                charCount++;
            }
    }
    //store all the information in the results array and return it
    result[0]=wordCount;
    result[1] = charCount;
    result[2] = ifHistory;
    result[3] = ifExit;
    return result;

}